"""Thai province-to-region mapping for coarse shop-location encoding."""

# Province names must match the cleaned suffixes produced by the feature
# engineer notebook (spaces/replaced by underscores, non-letters collapsed).
PROVINCE_TO_REGION = {
    # Bangkok metropolitan region
    "Bangkok": "bangkok_metro",
    "Nonthaburi": "bangkok_metro",
    "Pathum_Thani": "bangkok_metro",
    "Samut_Prakan": "bangkok_metro",
    "Samut_Sakhon": "bangkok_metro",
    "Nakhon_Pathom": "bangkok_metro",
    # Central
    "Ang_Thong": "central",
    "Chai_Nat": "central",
    "Lopburi": "central",
    "Nakhon_Nayok": "central",
    "Nakhon_Sawan": "central",
    "Phra_Nakhon_Si_Ayutthaya": "central",
    "Phichit": "central",
    "Phitsanulok": "central",
    "Saraburi": "central",
    "Sing_Buri": "central",
    "Suphan_Buri": "central",
    "Uthai_Thani": "central",
    "Chainat": "central",
    # Eastern
    "Chachoengsao": "eastern",
    "Chanthaburi": "eastern",
    "Prachin_Buri": "eastern",
    "Rayong": "eastern",
    "Sa_Kaeo": "eastern",
    "Trat": "eastern",
    "Chonburi": "eastern",
    # Western
    "Kanchanaburi": "western",
    "Phetchaburi": "western",
    "Prachuap_Khiri_Khan": "western",
    "Ratchaburi": "western",
    # Northern
    "Chiang_Mai": "northern",
    "Chiang_Rai": "northern",
    "Kamphaeng_Phet": "northern",
    "Lampang": "northern",
    "Lamphun": "northern",
    "Mae_Hong_Son": "northern",
    "Nan": "northern",
    "Phayao": "northern",
    "Phetchabun": "northern",
    "Phrae": "northern",
    "Sukhothai": "northern",
    "Tak": "northern",
    "Uttaradit": "northern",
    # Northeastern
    "Amnat_Charoen": "northeastern",
    "Bueng_Kan": "northeastern",
    "Buri_Ram": "northeastern",
    "Chaiyaphum": "northeastern",
    "Kalasin": "northeastern",
    "Khon_Kaen": "northeastern",
    "Loei": "northeastern",
    "Maha_Sarakham": "northeastern",
    "Mukdahan": "northeastern",
    "Nakhon_Phanom": "northeastern",
    "Nakhon_Ratchasima": "northeastern",
    "Nong_Bua_Lamphu": "northeastern",
    "Nong_Khai": "northeastern",
    "Roi_Et": "northeastern",
    "Sakon_Nakhon": "northeastern",
    "Si_Sa_Ket": "northeastern",
    "Surin": "northeastern",
    "Ubon_Ratchathani": "northeastern",
    "Udon_Thani": "northeastern",
    "Yasothon": "northeastern",
    # Southern
    "Chumphon": "southern",
    "Krabi": "southern",
    "Nakhon_Si_Thammarat": "southern",
    "Narathiwat": "southern",
    "Pattani": "southern",
    "Phang_Nga": "southern",
    "Phatthalung": "southern",
    "Phuket": "southern",
    "Ranong": "southern",
    "Satun": "southern",
    "Songkhla": "southern",
    "Surat_Thani": "southern",
    "Trang": "southern",
    "Yala": "southern",
    # Special
    "Unknown": "unknown",
    "ต_างประเทศ": "overseas",
}


KNOWN_REGIONS = sorted(set(PROVINCE_TO_REGION.values()))
